#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleObjCJSMNFoundation-import-private.h
src/reflect/_MulleObjCJSMNFoundation-include-private.h
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleObjCJSMNFoundation-import.h
src/reflect/_MulleObjCJSMNFoundation-include.h
)

set( PUBLIC_HEADERS
src/MulleJSMNParser.h
src/MulleObjCJSMNFoundation.h
src/MulleObjCLoader+MulleObjCJSMNFoundation.h
src/import.h
src/jsmn.h
)

