#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleJSMNParser.m
src/MulleObjCJSMNFoundation.m
src/MulleObjCJSMNFoundation-shlib.m
src/NSPropertyListSerialization+JSMN.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCJSMNFoundation.m
)
