/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use DAE9B674-2DEC-4CC3-8774-67CFE161AD71 instead of MulleObjCPlistFoundation if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleObjCPlistFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCPlistFoundation include whatever.h`
//    reorder:            `mulle-sde dependency move MulleObjCPlistFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCPlistFoundation [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleObjCPlistFoundation [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleObjCPlistFoundation [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleObjCPlistFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCPlistFoundation/MulleObjCPlistFoundation.h>   // MulleObjCPlistFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCJSMNFoundation-include.h")
#  include "_MulleObjCJSMNFoundation-include.h"
# endif
#endif

