/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_OBJC_PLIST_FOUNDATION_VERSION)
# if MULLE_OBJC_PLIST_FOUNDATION_VERSION < ((0 << 20) | (20 << 8) | 0)
#  error "MulleObjCPlistFoundation is too old"
# endif
# if MULLE_OBJC_PLIST_FOUNDATION_VERSION >= ((0 << 20) | (21 << 8) | 0)
#  error "MulleObjCPlistFoundation is too new"
# endif
#endif
