      { @selector( MulleObjCLoader), @selector( MulleFoundationBase) },      // 47a9beb6;MulleObjCLoader;efab19ea;MulleFoundationBase
      { @selector( MulleJSMNParser), MULLE_OBJC_NO_CATEGORYID },      // 11d4e75e;MulleJSMNParser;;
      { @selector( NSPropertyListSerialization), @selector( JSMN) },      // 87901b51;NSPropertyListSerialization;fc35d91b;JSMN
      { @selector( NSString), @selector( MulleJSMNParser) },      // 1994a171;NSString;11d4e75e;MulleJSMNParser
