#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/import-private.h
)

set( PUBLIC_HEADERS
src/MulleObjCJSMNFoundation.h
src/MulleObjCJSMNParser.h
src/MulleObjCLoader+MulleObjCJSMNFoundation.h
src/import.h
src/jsmn.h
)

