#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleObjCJSMNFoundation.m
src/MulleObjCJSMNFoundation-shlib.m
src/MulleObjCJSMNParser.m
src/NSPropertyListSerialization+JSMN.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCJSMNFoundation.m
)
